---
name: test workflow with wet run
on:
  pull_request:
jobs:
  wetrun_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Miniforge and mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          mamba-version: '*'
          use-mamba: true
          conda-solver: libmamba
          auto-activate-base: true
      - name: Create environment with snakebids
        run: |
          mamba create -n snakebids-env snakebids scikit-learn pandas -c bioconda -c conda-forge -y
      - name: Cache Snakemake Conda environments
        uses: actions/cache@v4
        with:
          path: test_data/labelmerge_cache_dir/conda
          key: conda-env-${{ hashFiles('labelmerge/workflow/envs/*.yaml') }}
          restore-keys: |
            conda-env-
      - name: Set LABELMERGE_CACHE_DIR
        run: |
          echo "LABELMERGE_CACHE_DIR=`pwd`/test_data/labelmerge_cache_dir" >> $GITHUB_ENV
      - name: Run wet-run test for cortical and subcortical files
        shell: bash -l {0}
        run: |
          conda activate snakebids-env
          ./labelmerge/run.py test_data/bids_wetrun_testing/tpl-MNI152NLin2009cAsym test_out participant \
            --base-desc 100Parcels7Networks --overlay_bids_dir test_data/bids_wetrun_testing/tpl-MNI152NLin2009cAsym \
            --overlay_desc tn --cores all --force-output --conda-frontend mamba | tee labelmerge_output.log